### PR TITLE
Disable line wrapping when converting JSON to YAML

### PR DESCRIPTION
**Pull request by mprahl**
This allows users to have lines over 80 characters with template strings
in them without causing errors. For example, the following YAML would
cause the template resolution to fail even though it is valid YAML:
```yaml
message: '{{ "VGhpcyBpcyBhIHJlYWxseSByZWFsbHkgcmVhbGx5IGxvbmcgc2VudGVuY2UgdGhhdCBpcyBkZWZpbml0ZWx5IG1vcmUgdGhhbiA4MCBjaGFyYWN0ZXJzIHRvIHRlc3QgdGhpcyBvdXQu" | base64dec }}'
```

Please note that this change is not user facing other than fixing the
situation mentioned previously.

This is fixed by using yaml.v3 when converting the JSON to YAML instead
of sigs.k8s.io/yaml which uses yaml.v2 under the hood. This version has
line wrapping disabled by default. Version 2 can only have line wrapping
disabled globally, which is not desired since consumers of this library
may rely on line wrapping for other reasons.

### CODE REVIEW

**Comment by mprahl** [comment]
@gparvin and @ckandag could you please review and provide your opinion on if we should do this?

**Comment by gparvin** [comment]
Yes, this fix sounds great to me.

**Comment by mprahl** [comment]
@ckandag and @gparvin, I just included a unit test to ensure there is no regression.

Could you please review this PR?

**Review by gparvin — APPROVED** [review]
This looks good.  Thanks for the PR

**Pull request merged**
